### ISSUE TITLE
Implement user login

### ISSUE THREAD

**Issue by gbrova** [adityadhara/RA-Scheduler#1]
For example, see part 4 of the tutorial:
http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-v-user-logins

**Comment by thenomadlad** [comment]
access a user's data with g.user or current_user (from flask.ext.login)

**Comment by thenomadlad** [comment]
Also, this prompted db change. I would suggest deletion of main.db before you run flask (ie before "run.py" is executed) so that main.db is reset
