### ISSUE TITLE
Menu bar positions should highlight the active page

### ISSUE THREAD

**Issue by gbrova** [adityadhara/RA-Scheduler#3]
Currently, "Home" always appears active. This is incorrect if the user is now at a different tab. We should fix this.

**Comment by gbrova** [comment]
Fixed at commit 6a92e5d5. 

Solution was to programmatically add the menu items using jinja templates, then for individual pages' templates, mark them as active with something like 
{% set active_page = "view_schedules" %}

For details, see stackoverflow thread: http://stackoverflow.com/questions/18600031/

**Comment by thenomadlad** [comment]
two changes:
1 - added href="#" to current pages
2 - separated nav bar into "default" "user" and "non-user" buttons
